import React from 'react';

    const employees = [
    {
        "id": 1,
        "name": "Jason Stasum",
        "experience":"Have had years of frycook experience. I have also worked in the white house and can do a double backflip. Also great with kids.",
        "education":"Ringling College of the Arts",
        "skills":"Can do magic and Restore a car",
        "viewed":"False",
        "match":"False",
        "jobTitle":"Dolphin Trainer",
        
    },
    {
        "id": 2,
        "name": "Bob Ross",
        "experience":"I have lived in the mean streets of detroit all my life and am now just looking for a nice cozy job. I have wrestled gators and fought in the Spanish War. Also great with kids",
        "education":"Mellowbrook High School",
        "skills":"Carpentry, Sewing, Croucheting, Knitting",
        "viewed":"False",
        "match":"False",
        "jobTitle":"Dolphin Caretaker",
    },
    {
        "id": 3,
        "name": "Dorothy Drew",
        "experience":"I have never had a job, but I've got spunk, and gingovitus. Also great with kids",
        "education":"School of Hard Knocks",
        "skills":"Programming in: JavaScript, Python, C, C#, Binary",
        "viewed":"False",
        "match":"False",
        "jobTitle":"Dolphin Enthusiast",
    },
    {
        "id": 4,
        "name": "Marge Simpson",
        "experience":"I am a stay at home mom, but I used to be a great journalist before I got pregnant. Raising them was my experience, it still haunts me",
        "education":"Trade School",
        "skills":"Cooking and cleaning, laundry and minor house repair",
        "viewed":"False",
        "match":"False",
        "jobTitle":"Dolphin Impersonator",
    },
    {
        "id": 5,
        "name": "Apolo Creed",
        "experience":"I have so much experience I could not even begin to explain",
        "education":"Grade School",
        "skills":"Teaching dolphins at Mote Marine and SeaWorld",
        "viewed":"False",
        "match":"False",
        "jobTitle":"Dolphin Trainer",
    },
    {
        "id": 6,
        "name": "Gary Oldman",
        "experience": "Have worked at PetSmart and PetCo, they made me clean the garbage",
        "education": "3 years of culinary school, 4 years of buisness school, 7 years of dance school",
        "skills": "I can shoot a can off a mans head from forty miles away with a double barrel shotgun",
        "viewed": "False",
        "match": "False",
        "jobTitle": "Dolphin Nurse",
    },
    {
        "id": 7,
        "name": "Justin Avery",
        "experience": "I used to debug code for apple and napster",
        "education": "Jerry West Elementary",
        "skills": "JavaScript, C, C+, C++, C+++, C-, C+-+, C#",
        "viewed": "False",
        "match": "False",
        "jobTitle": "Dolphin Trainer",
    },
    {
        "id": 8,
        "name": "Carly Rae",
        "experience": "I have worked on a lot of cars before and after the 1940's. Also used to work in as a retailer who sold car parts. Also great with kids",
        "education": "Trade School, and Private School",
        "skills": "can repair mufflers, tires, radios, alarm clocks",
        "viewed": "False",
        "match": "False",
        "jobTitle": "Dolphin Researcher",
    },
    {
        "id": 9,
        "name": "Edgar Write",
        "experience": "I have directed movies like Driver Baby, Hot Fuzz, Shawn of the Dead. Also great with kids",
        "education": "Film School, Harvard",
        "skills": "I can fit my whole fist in my mouth",
        "viewed": "False",
        "match": "False",
        "jobTitle": "Dolphin Caretaker",
    },
    {
        "id": 10,
        "name": "Harold Flower",
        "experience": "Used to be a cheap old typewad until the flying dutchman came to put me in Davy Jones Locker, I have seen the error of my ways and just want to make an honest living as a doctor",
        "education": "dropout",
        "skills": "Can manage a whole resteraunt, great with money",
        "viewed": "False",
        "match": "False",
        "jobTitle": "Dolphin Trainer",

    }

]

   export default employees;